const CONFIG = {
  // 코스피 상위 30
  WATCHLIST_KR: [
    { code: '005930', name: '삼성전자' },
    { code: '000660', name: 'SK하이닉스' },
    { code: '005380', name: '현대차' },
    { code: '000270', name: '기아' },
    { code: '051910', name: 'LG화학' },
    { code: '006400', name: '삼성SDI' },
    { code: '068270', name: '셀트리온' },
    { code: '003670', name: '포스코퓨처엠' },
    { code: '035420', name: 'NAVER' },
    { code: '035720', name: '카카오' },
    { code: '207940', name: '삼성바이오로직스' },
    { code: '105560', name: 'KB금융' },
    { code: '055550', name: '신한지주' },
    { code: '086790', name: '하나금융지주' },
    { code: '316140', name: '우리금융지주' },
    { code: '032830', name: '삼성생명' },
    { code: '017670', name: 'SK텔레콤' },
    { code: '030200', name: 'KT' },
    { code: '009150', name: '삼성전기' },
    { code: '028260', name: '삼성물산' },
    { code: '012330', name: '현대모비스' },
    { code: '066570', name: 'LG전자' },
    { code: '034730', name: 'SK' },
    { code: '015760', name: '한국전력' },
    { code: '033780', name: 'KT&G' },
    { code: '003550', name: 'LG' },
    { code: '010950', name: 'S-Oil' },
    { code: '096770', name: 'SK이노베이션' },
    { code: '010140', name: '삼성중공업' },
    { code: '000810', name: '삼성화재' },
  ],

  // S&P 500 상위 30
  WATCHLIST_US: [
    { symb: 'NVDA', excd: 'NAS', name: 'NVIDIA' },
    { symb: 'AAPL', excd: 'NAS', name: 'Apple' },
    { symb: 'MSFT', excd: 'NAS', name: 'Microsoft' },
    { symb: 'AMZN', excd: 'NAS', name: 'Amazon' },
    { symb: 'GOOGL', excd: 'NAS', name: 'Alphabet' },
    { symb: 'META', excd: 'NAS', name: 'Meta' },
    { symb: 'TSLA', excd: 'NAS', name: 'Tesla' },
    { symb: 'AVGO', excd: 'NAS', name: 'Broadcom' },
    { symb: 'JPM', excd: 'NYS', name: 'JPMorgan' },
    { symb: 'WMT', excd: 'NYS', name: 'Walmart' },
    { symb: 'LLY', excd: 'NYS', name: 'Eli Lilly' },
    { symb: 'V', excd: 'NYS', name: 'Visa' },
    { symb: 'COST', excd: 'NAS', name: 'Costco' },
    { symb: 'MA', excd: 'NYS', name: 'Mastercard' },
    { symb: 'NFLX', excd: 'NAS', name: 'Netflix' },
    { symb: 'UNH', excd: 'NYS', name: 'UnitedHealth' },
    { symb: 'XOM', excd: 'NYS', name: 'ExxonMobil' },
    { symb: 'HD', excd: 'NYS', name: 'Home Depot' },
    { symb: 'ORCL', excd: 'NYS', name: 'Oracle' },
    { symb: 'BAC', excd: 'NYS', name: 'Bank of America' },
    { symb: 'AMD', excd: 'NAS', name: 'AMD' },
    { symb: 'PG', excd: 'NYS', name: 'P&G' },
    { symb: 'ABBV', excd: 'NYS', name: 'AbbVie' },
    { symb: 'CRM', excd: 'NYS', name: 'Salesforce' },
    { symb: 'KO', excd: 'NYS', name: 'Coca-Cola' },
    { symb: 'MRK', excd: 'NYS', name: 'Merck' },
    { symb: 'CVX', excd: 'NYS', name: 'Chevron' },
    { symb: 'ACN', excd: 'NYS', name: 'Accenture' },
    { symb: 'PEP', excd: 'NAS', name: 'PepsiCo' },
    { symb: 'PLTR', excd: 'NYS', name: 'Palantir' },
  ]
};
